# template YAML from https://raw.githubusercontent.com/rsoesemann/codeclimate-apexmetrics/master/resources/.codeclimate.yml
engines:
  apexmetrics:
    enabled: true
ratings:
  paths:
    - "**.cls"
    - "**.trigger"
    - "**.component"
    - "**.page" 
exclude_paths:
  - "src/documents/"
  - "**.schema"
  - "**.xml"
  - "**.actionLinkGroupTemplate"  
  - "**.snapshot" 
  - "**.appMenu"
  - "**.approvalProcess"  
  - "**.assignmentRules"
  - "**.authprovider" 
  - "**.autoResponseRules"
  - "**.callCenter" 
  - "**.crt"
  - "**.channelLayout"  
  - "**.community"
  - "**.connectedApp" 
  - "**.corsWhitelistOrigin"
  - "**.app"  
  - "**.customApplicationComponent"
  - "**.feedFilter" 
  - "**.labels"
  - "**.md" 
  - "**.object"
  - "**.objectTranslation"  
  - "**.weblink"
  - "**.customPermission" 
  - "**.site"
  - "**.tab"  
  - "**.dashboard"
  - "**.datacategorygroup"  
  - "**.delegateGroup"
  - "**.email"  
  - "**.escalationRules"
  - "**.dataSource" 
  - "**.flexipage"
  - "**.flow" 
  - "**.flowDefinition"
  - "**.group"  
  - "**.homePageComponent"
  - "**.homePageLayout" 
  - "**.installedPackage"
  - "**.layout" 
  - "**.letter"
  - "**.matchingRule" 
  - "**.namedCredential"
  - "**.pathAssistant"  
  - "**.permissionset"
  - "**.cachePartition" 
  - "**.portal"
  - "**.postTemplate" 
  - "**.profile"
  - "**.queue"  
  - "**.quickAction"
  - "**.remoteSite" 
  - "**.report"
  - "**.reportType" 
  - "**.role"
  - "**.samlssoconfig"  
  - "**.scf"
  - "**.settings" 
  - "**.sharingRules"
  - "**.sharingSet"
  - "**.site" 
  - "**.resource"
  - "**.synonymDictionary"
  - "**.transactionSecurityPolicy"  
  - "**.workflow"
  - "**.xorghub"
  - "**.globalPicklist"
  - "**.translation"
  
